version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: batch_schema
      MYSQL_USER: batch_user
      MYSQL_PASSWORD: batchuser
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/db/Product_Queries.sql:/docker-entrypoint-initdb.d/Product_Queries.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poc-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/batch_schema
      SPRING_DATASOURCE_USERNAME: batch_user
      SPRING_DATASOURCE_PASSWORD: batchuser
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources:/app/resources

volumes:
  db_data:
